version: '3.1'
services:
  order:
    container_name: ordercontainer
    image: orderimage
    build: ./
    ports:
      - "8083:8083"
    depends_on:
      - orderpostgreservice
  orderpostgreservice:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=orderdb   
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE= http://eurekaserver:8070/eureka          
    volumes:
      - ./src/main/resources/sql/orderinit.sql:/docker-entrypoint-initdb.d/orderinit.sql